version: '3.7'
services:
    front_end:
        build:
            context: ./service_1
        ports:
            - "5000:5000"
        environment: 
            - MYSQLHOST=${MYSQLHOST}
            - MYSQLUSER=${MYSQLUSER}
            - MYSQLPASSWORD=${MYSQLPASSWORD}
            - MYSQLDB=${MYSQLDB}
    part_one:
        build:
            context: ./service_2
        ports:
            - "5001:5001"
    part_two:
        build:
            context: ./service_3
        ports:
            - "5002:5002"
    end_product:
        build:
            context: ./service_4
        ports:
            - "5003:5003"