version: '3.7'
 services:
     front_end:
         image: dhulsman/service_1:latest
         environment: 
             - MYSQLHOST=${MYSQLHOST}
             - MYSQLUSER=${MYSQLUSER}
             - MYSQLPASSWORD=${MYSQLPASSWORD}
             - MYSQLDB=${MYSQLDB}
         deploy:
             replicas: 3
         networks:
             - service_network
     part_one:
         image: dhulsman/service_2:latest
         deploy:
             replicas: 3
         networks:
             - service_network
     part_two:
         image: dhulsman/service_3:latest
         deploy:
             replicas: 3
         networks:
             - service_network
     end_product:
         image: dhulsman/service_4:latest
         deploy:
             replicas: 3
         networks:
             - service_network
     nginx_for_rapper:
         image: dhulsman/service_nginx:latest
         ports:
             - "80:80"
         networks:
             - service_network
         depends_on: 
             - front_end
             - part_one
             - part_two
             - end_product
         deploy:
             replicas: 3
 networks:
     service_network:
         driver: overlay