version: '3.7'
services:
    front_end:
        image: dhulsman/service_1:latest
        ports:
            - "5000:5000"
        environment: 
            - MYSQLHOST=${MYSQLHOST}
            - MYSQLUSER=${MYSQLUSER}
            - MYSQLPASSWORD=${MYSQLPASSWORD}
            - MYSQLDB=${MYSQLDB}
        deploy:
            replicas: 3
        networks:
            - service_network
    part_one:
        image: dhulsman/service_2:latest
        ports:
            - "5001:5001"
        deploy:
            replicas: 3
        networks:
            - service_network
    part_two:
        image: dhulsman/service_3:latest
        ports:
            - "5002:5002"
        deploy:
            replicas: 3
        networks:
            - service_network
    end_product:
        image: dhulsman/service_4:latest
        ports:
            - "5003:5003"
        deploy:
            replicas: 3
        networks:
            - service_network
networks:
    service_network:
        driver: overlay